### ISSUE TITLE
Error reading Ultrasonic with id:regenfass

### ISSUE THREAD

**Issue by thost96** [wutu/pimatic-ultrasonic#5]
Hi,

after installing the ultrasonic plugin and configuring my device it got spamed with this error: 

`error [pimatic-ultrasonic]: Error reading Ultrasonic with id:regenfass`

I already checked my config and theres no error. Maybe som bug in the plugin itself?

**Comment by wutu** [comment]
Hey, you're the most confident of the hardware work?
This error evoke disconnected Echo or Trigger wire (resp. negative reading).

**Comment by thost96** [comment]
i had some voltage issues. This can be closed.
